### ISSUE TITLE
instant lookup doesn't follow space change

### ISSUE THREAD

**Issue by yangkennyk** [tkainrad/keycombiner#10]
**Describe the bug**
If I open instant lookup on space 1 then change to space 2, triggering instant lookup reverts back to space 1

**To Reproduce**
1. open keycombiner on space 1 and trigger instant look up
2. change to space 2
3. trigger instant lookup
4. reverts back to space 1

**Comment by tkainrad** [comment]
Ah, that's a very helpful observation and bug report! This should be doable and will be fixed with the next KeyCombiner Desktop version that will be released within April.

Thanks!

**Comment by tkainrad** [comment]
This is now fixed in version 0.1.9! On macOS, please download from https://keycombiner.com/desktop/ and reinstall.

Took quite a bit of testing to get this right. Fullscreen apps with their own (work)space were a bit tricky. Please let me know if everything works as you would expect.

Something else that I noticed that might be interesting:  
When KeyCombiner is not shown in the dock (because the main window was closed) and you use the instant lookup, restoring focus to the previous application via <kbd>cmd</kbd>+<kbd>tab</kbd> does not work.  
Instead, macOS will switch to the application you used before the previous application because apps that are not present in the dock are not counted. It still works via <kbd>Esc</kbd> or pressing the lookup trigger again. However, if you want to use <kbd>cmd</kbd>+<kbd>tab</kbd>, you will need to keep the main window in minimized state instead of closing it.
