### ISSUE TITLE
Please update to latest Figma shortcuts

### ISSUE THREAD

**Issue by angyb** [tkainrad/keycombiner#102]
Thank you for a great product!

**Is your feature request related to a problem? Please describe.**
Figma 116.6.3 has several new and changed shortcuts not reflected in your page: https://keycombiner.com/collections/figma/

**Describe the solution you'd like**
Update https://keycombiner.com/collections/figma/ with latest Figma shortcuts
Ideally include shortcuts for File & Properties and other menu items as well.

**Describe alternatives you've considered**
https://usethekeyboard.com/figma/
https://shortcuts.design/tools/toolspage-figma/

**Additional context**

**Comment by angyb** [comment]
I've created an updated version of your Public Figma Shortcuts in my paid account. You are very welcome to publish it if you like. https://keycombiner.com/collecting/collections/shared/aa11ccbb-9c1c-4a47-aab0-ab72cf5da955

I used "opt" instead of "alt" because I will be sharing this internally with other Mac users who have an Option key, not an Alt key.

My CSV: 
[Angy Figma Shortcuts.csv](https://github.com/tkainrad/keycombiner/files/10678229/Angy.Figma.Shortcuts.csv)

**Comment by tkainrad** [comment]
The updated Figma collection is now live at https://keycombiner.com/collections/figma/

Thanks for sharing your collection, that was helpful. I noticed a couple differences between your collection and the official Figma in-app table for US-QWERTY though:
- plus/- instead of cmd+plus/-
- different shortcut for _Ungroup selection_
- Figma doesn't list shift for the opacity shortcuts, just numbers without modifiers
- Some of the shortcuts you list in _Other_ are already in other categories like _Place Image_, _Select All/Inverse_ or _Search/Quick Actions_

Thanks for bringing this to my attention, Figma really did update quite a few shortcuts.
