### ISSUE TITLE
Figma shortcuts on MacOS - Some are incorrect?

### ISSUE THREAD

**Issue by slt-uxd** [tkainrad/keycombiner#13]
https://keycombiner.com/collections/figma/macos/

**Bring to Front and Send to Back**
Modifiers are Alt+Cmd, not Shift+Cmd for me on my Mac. 

**Zoom In**
= , not +

**Comment by tkainrad** [comment]
Thanks for reporting this problem!

You are absolutely right. The _Bring to Front_ and _Send to Back_ shortcuts have the wrong modifiers. We will fix that within the day.

Regarding _Zoom in_, I am not so sure.

Figma does list it as <kbd>+</kbd>:

![image](https://user-images.githubusercontent.com/7394822/114388766-70828880-9b94-11eb-9c7c-df4e5b68f0d5.png)

However, I believe in practice both <kbd>+</kbd> and <kbd>=</kbd> are allowed as a means to support different keyboard layouts. We will set it to <kbd>+</kbd> or <kbd>=</kbd> for KeyCombiner.

Please note that you can always edit shortcuts in your personal collections if the defaults do not work for you because of layout issues or w/e. Nevertheless, we are grateful for reports about wrong combinations in our public collections.

**Comment by slt-uxd** [comment]
> Thanks for reporting this problem!
> 
> You are absolutely right. The _Bring to Front_ and _Send to Back_ shortcuts have the wrong modifiers. We will fix that within the day.
> 
> Regarding _Zoom in_, I am not so sure.
> 
> Figma does list it as +:
> 
> ![image](https://user-images.githubusercontent.com/7394822/114388766-70828880-9b94-11eb-9c7c-df4e5b68f0d5.png)
> 
> However, I believe in practice both + and = are allowed as a means to support different keyboard layouts. We will set it to + or = for KeyCombiner.
> 
> Please note that you can always edit shortcuts in your personal collections if the defaults do not work for you because of layout issues or w/e. Nevertheless, we are grateful for reports about wrong combinations in our public collections.

Looks like both = and + work for zooming in, at leasy on my Mac, using standard US keyboard layout & hardware

**Comment by tkainrad** [comment]
KeyCombiner's Figma collection is now updated, thanks again for reporting the errors!
