### ISSUE TITLE
Shortcut lists are empty

### ISSUE THREAD

**Issue by elchead** [tkainrad/keycombiner#18]
**Describe the bug**
All of my shortcut collections appear as empty since a few days. I can still train the collections but I cannot edit them, because the table is empty.

**To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/29373967/120706366-488b1380-c4b9-11eb-8a57-37b848a62d31.png)

**Additional context**

**Comment by tkainrad** [comment]
Huh, that's a serious bug if there ever was one. Thanks for reporting it!

Since a few days ago, KeyCombiner loads the shortcuts in the background after navigating to the page and adds them to the table. It looks like this background call is not working for you. Unfortunately, I have no idea why this could be the case.

Could you open the developer console (by pressing <kbd>F12</kbd> in Chrome), go to the _Console_ tab, and then load one of your personal collections? I would expect some error message there. The only explanation that I have is that your browser blocks the backend call for some reason. Or are you using [KeyCombiner Desktop](https://keycombiner.com/desktop/)?

**Comment by elchead** [comment]
Hi Thomas,

I only get this output on the console:
DevTools failed to load source map: Could not load content for chrome-extension://abkfbakhjpmblaafnpgjppbmioombali/lib/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

But I think it is not related to your website.
Also, the same happens with the Desktop app. But I'd guess that it uses electron or something similar?

I'd be happy to help with finding this issue :) The source code is not public right?

**Comment by tkainrad** [comment]
Thanks for reporting back.

I think I found the problem. A backend request was restricted to _Pro_ users even though it shouldn't have been. That will teach me to test any substantial change with both a _Pro_ and a regular user account.

If you are interested, I'd be happy to send you a 70% price reduction code for _KeyCombiner Pro_ as a thank-you gift for reporting this serious problem.

---
The desktop app is indeed an electron app. However, there is some fine-tuning compared to the web application. Also, if something does not work with the desktop app, it means that the problem does not come from a browser extension or an outdated browser version that does not support some API.

KeyCombiner is not open-source at this time. At some point, I would like to make the desktop client open-source.

**Comment by elchead** [comment]
Yes, its fixed now :) Sure, I'd be happy to take this offer to support the project
