### ISSUE TITLE
Show number of selected items in "Collect selected" button

### ISSUE THREAD

**Issue by berknas** [tkainrad/keycombiner#3]
**Is your feature request related to a problem? Please describe.**
When I add keyboards from a public collection to my private ones, I want to keep the number of new shortcuts to a small number to avoid feeling overwhelmed while training (e.g., max 10 new items per day). Right now, it feels difficult to keep track of the number of selected items (you have to scroll down all the way to the table footer to see this information).

**Describe the solution you'd like**
Instead of "collect selected", the button could include the number of selected elements, e.g. "collect selected 8".

**Describe alternatives you've considered**
Maybe instead you could provide an input element where you can specify the max number of new elements to add and Keycombiner would warn you if you select more elements.

**Additional context**
![image](https://user-images.githubusercontent.com/74780423/111110553-06f36800-855d-11eb-9f36-14195597a306.png)

**Comment by tkainrad** [comment]
Thank you for the detailed request!

I agree, it's definitely far from ideal that you have to scroll down to the bottom of the table to see the number of currently selected items. I like your proposed solution. The only issue I see is with personal collections, where this would apply to several buttons (_Copy_, _Move_, _Delete_). Also, the button sizes should not increase because of the selection, which could be an issue when a large number of combinations are selected (several digits).

I am also thinking about showing it when you hover over the button, but that's probably not very intuitive. I will think about it, and hopefully, implement a solution soon.

**Comment by tkainrad** [comment]
This took quite a bit longer than I thought, but I am happy to announce that it's done!

Went back and forth on a couple of different solutions. Unfortunately, displaying the number in the button came with a number of problems, mainly those described in my previous comment.

The number of selected rows is now displayed next to the page length dropdown at the top left of the table:

![image](https://user-images.githubusercontent.com/7394822/116456542-aeed9800-a862-11eb-87c6-18d34b82f46c.png)

This is in addition to the existing display at the bottom of the table. Now, it should be easy to see the number independent of scroll position.

I hope this solves the issue for you, thanks again for the request!
