### ISSUE TITLE
Error report for keycombiner 0.3.3 - when running automatic update from menu

### ISSUE THREAD

**Issue by lisaross** [tkainrad/keycombiner#44]
Error:
```Error: Cannot download "https://keycombiner.com/download/KeyCombiner-0.3.4-mac.zip", status 404: 
    at ClientRequest.<anonymous> (/Applications/KeyCombiner.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:250:26)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6254)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```
OS: macOS 10.16

I'll not run the manual update in case you need any help troubleshooting this - let me know if you have what you need and I'll stand down LOL

**Comment by tkainrad** [comment]
Thanks for reporting this, it's probably the same issue as #30. 

I wouldn't want you to keep you from updating manually. A couple of minor questions maybe: 

1. Did auto-updating KeyCombiner Desktop ever work for you? I.e from previous versions to 0.3.3?
2. What happens when you restart KeyCombiner Desktop? The auto-udpate should also trigger on restart, not just via the menu item.
3. Do you have any network configuration that is out of the ordinary? Maybe a proxy setup?

If any of these questions are hard to answer, please just go ahead and update manually ;)

**Comment by lisaross** [comment]
Here's the answers to your questions:
1. This is the first time I've tried so I'm not sure
2. Restarting the app doesn't trigger the auto-update and I'm getting the same error when I use the menu item
3. My network is pretty vanilla - no VPN or proxy
I'm going to go download manually then, but if there's anything I can send you (logs maybe?) I have my computer backed up so I should be able to grab older file versions. LMK if I can help.
