### ISSUE TITLE
Add a "Star" button to entries

### ISSUE THREAD

**Issue by y-vasyunin** [tkainrad/keycombiner#60]
Let's say, I have 150 entries in one collection. They all seem useful to me, but to memorize such a big list of shortcuts I'd like to prioritize the entries, so that I firstly learn those that I plan to use more. Would it be possible to add some "Star" button, which adds more weight to such prioritized entries?

**Comment by tkainrad** [comment]
Hi, thanks for this suggestion!

This whole thing has been an important issue for KeyCombiner since the beginning. There are now many features that are supposed to help you in this situation. I have hopes that there is something already implemented that can help you:

- A practice run never includes more than 15 combinations with confidence of less than 1. So, even if you just practice the entire collection, practice will gradually include more combinations.
- There are now [courses](https://keycombiner.com/courses/) for some applications that provide a guided practice experience and enable you to learn in easy to grasp lessons.
- You can select only part of a collection for practice.
- Since very recently, there is a [dedicated spaced repetition mode ](https://github.com/tkainrad/keycombiner/wiki/Spaced-Repetition) that takes complete care of deciding which combinations are due for review.
- Personally, I like to gradually expand my collections. This is quite convenient with KeyCombiner as a public collection shows which combinations are already in your personal collections (and in which by hovering over the icon).
- If none of the above works for you, maybe you can just make a separate personal collection for the ones you want to practice first? You can then gradually move more and more combinations into that collection. KeyCombiner will automatically show the combinations with lower confidence values more often during practice.

I am not too much into the idea of adding an additional, manual method to select combinations for prioritized practice. What should happen once you learned them? Do you have to manually remove the "star" again? I have the feeling this would be rather complex and rarely used.

**Comment by y-vasyunin** [comment]
> This is quite convenient with KeyCombiner as a public collection shows which combinations are already in your personal collections (and in which by hovering over the icon).

I didn't know about this feature. It seems that it would work for me, thank you.

**Comment by tkainrad** [comment]
Thanks for reporting back, I am glad this works for you! It's also how I created and gradually learned most of my collections.
