### ISSUE TITLE
Collections Won’t Load on iPad Mini

### ISSUE THREAD

**Issue by QueensDeeJay** [tkainrad/keycombiner#7]
To see if KC would work on an iPad Mini, I dug one out of mothballs to give it a try. It may be too old. This is what happens:

I'm able to log into KC and can see/use the dashboard, but when I try to call up a particular collection, it doesn't come up. It looks like KC is trying to comply in that the name of the collection is displayed; the 3-dot menu shows up; as does the Practice Control buttons, though the count of Mastered Shortcuts is highlighted and blank. Please see in the screenshot. ![image](https://user-images.githubusercontent.com/7013913/111634320-c732b780-87cc-11eb-9aac-462ac1644ed2.jpeg)

Thoughts?

**Comment by tkainrad** [comment]
Thanks for reporting this problem. Unfortunately, I don't think we will have the resources to work on this. The problem is likely that the device uses an outdated browser, which does not provide some of the API's that KeyCombiner relies on.

You might be able to work around this problem if you can install a different browser. Not sure though how that works on an iPad Mini.

**Comment by QueensDeeJay** [comment]
![F76B8813-6BF9-40AB-A955-BD498C294BF2](https://user-images.githubusercontent.com/7013913/111709433-f887a380-881d-11eb-8567-7e90be22a932.png)
Once I read your comment and then updated my iPad Mini’s browser to Chrome, KC was able to perform normally on the Mini. Thx for the hint! :)

**Comment by tkainrad** [comment]
That's great to hear, thanks for reporting back!
