### ISSUE TITLE
`prtsc` key should be a valid key

### ISSUE THREAD

**Issue by brimwats** [tkainrad/keycombiner#70]
It is unclear from the wiki if printscreen is supported or not: https://github.com/tkainrad/keycombiner/wiki/Valid-Key-Combinations

**Comment by tkainrad** [comment]
Hi, thanks for bringing this up!

At the moment, <kbd>PrntScrn</kbd> is not supported. The idea with the wiki would be that it lists all keys that are supported. So, if a key is not listed, it is not considered valid and combinations containing the key will not be included during practice. You can still use invalid keys in your collections though. 

That being said, I can't really think of a reason why <kbd>PrntScrn</kbd> is currently treated as invalid. I will probably include it in the future. Just to make sure we don't have a misunderstanding, do you want it to be treated as a valid key?

**Comment by brimwats** [comment]
I would *love* for it to be supported! Was trying to figure out how to get ShareX commands in my collection. Here all are the default ones (for taking) are!
![image](https://user-images.githubusercontent.com/73113656/153757168-2a79d3e5-741b-4993-a554-62df35c310ab.png)

**Comment by tkainrad** [comment]
Thanks for the screenshot. Adding _ShareX_ together with supporting the <kbd>PrntScrn</kbd> key would surely make sense. Are you sure these are all the shortcuts? There seem to be [some others listed on their website](https://getsharex.com/docs/region-capture). 

Btw, you can still get the shortcuts into your collections by just typing them in. You don't necessarily have to record them.

**Comment by brimwats** [comment]
> Thanks for the screenshot. Adding ShareX together with supporting the PrntScrn key would surely make sense. Are you sure these are all the shortcuts? There seem to be [some others listed on their website](https://getsharex.com/docs/region-capture).

that's what i meant by the default ones for (taking) are! But yes, thanks for the pointer. ShareX has an insane amount of hidden tools
![image](https://user-images.githubusercontent.com/73113656/153782012-c72ed365-47cf-4ad6-8fbe-bfc6f0a598a4.png)

> Btw, you can still get the shortcuts into your collections by just typing them in. You don't necessarily have to record them.

I got aroud it right now by pretending that F12 is the same as PrntScrn bc they're next to each other on my keyboard

**Comment by tkainrad** [comment]
I am glad you found a workaround. Turns out adding the <kbd>PrintScreen</kbd> key isn't that easy. The default key processing happens using the `keyCode` property, which doesn't work for this special key. I will be looking for solutions, but don't expect this to happen soon. I really hope the workaround is working for you!

**Comment by brimwats** [comment]
no worries! was worried that might br a harder one

**Comment by tkainrad** [comment]
Turns out it's not actually that hard. I was using my own code for shortcut processing for a while anyway and have already in the past added custom keys (e.g. `numlock`). Not sure why I wasn't thinking about that.

Anyway, the _Print Screen_ key is now supported as `prtsc`. It can be recorded and practiced like all the other [valid key combinations](https://github.com/tkainrad/keycombiner/wiki/Valid-Key-Combinations).

Thanks for your suggestion!

**Comment by brimwats** [comment]
amazing!! thanks so much
