### ISSUE TITLE
Request: Add Chromebook keyboard layout and Chrome OS collection

### ISSUE THREAD

**Issue by Prometheus720** [tkainrad/keycombiner#71]
I am a public school teacher and Chromebooks are **extremely** common here. They have a non-standard keyboard layout (most notably a tenkeyless layout which also changes caps lock into a launcher key and changes the generic function keys to Chromebook-specific functions). 

They also represent a 4th "desktop" operating system with its own set of commands and shortcuts.

I would like to use KeyCombiner at our school to help train teachers and students to use keyboard shortcuts, and we plan on doing so while just focusing on Google Chrome and Google Workspace shortcuts. However, having the additional capability of Chromebook-specific features would be incredible and would result in a sea change in how we work with technology at our school.

I would be very satisfied with simply adding Chromebook shortcuts into a collection. I imagine that this process would be much less trouble than adding an entire new keyboard layout.

I really love the app so far for my own use (mainly Notion so far). You know something is clever when you say, "It is really ridiculous that nobody thought of this before." Thank you so much for your time and generosity.

**Comment by tkainrad** [comment]
Hi, I am very excited to hear that! I always thought that it would be very rewarding for students if they learned basic shortcuts in school.

I don't think I will be able to make a lot of Chromebook-specific improvements as long as I don't own one myself. However, I am very open to low-hanging fruits like having a public collection. 

Are these the shortcuts you would like to see in such a collection: https://support.google.com/chromebook/answer/183101?hl=en ?
I will have to think a bit about how to include the Chromebook-specific keys (Launcher, Search, Rotate).

**Comment by Prometheus720** [comment]
Yes, that collection would be a **great** start! 

As for the Chromebook keys, my model has them replacing keys F1-F11. It is very similar to how some laptop manufacturers use these as media playback keys/brightness keys but allow users to modify them with an Fn button. There is actually a similar setting on Chromebooks which allows for modification of those keys to act like proper function keys.

So the simplest thing would be to place the functions shown [here](https://cdn6.bigcommerce.com/s-blhknq8/product_images/uploaded_images/screen-shot-2016-05-09-at-5.20.34-pm.png?t=1462839777) on the F1-F11 keys. As far as I can tell the Chromebook layout is identical across models. And you would need to add in caps lock as search. No need to edit the keyboard layout image--just don't use some keys.

So back would just be F1. You can ignore the fact it is called the Back key or whatever.

**Comment by tkainrad** [comment]
There is now a Chromebook collection: https://keycombiner.com/collections/chromebook/ :partying_face: 

Thanks for making the request!

As per your advice, I substituted the top row keys with regular function keys. 

Furthermore, I replaced <kbd>Search</kbd>/<kbd>Launcher</kbd> with <kbd>Meta</kbd>. KeyCombiner uses <kbd>Meta</kbd> to denote the <kbd>Windows</kbd> key on Windows and Launcher-key on Linux. I believe it is the correct analogy for the Chromebook <kbd>Launcher</kbd> key, even though it is at a different position. Especially since the <kbd>Windows</kbd> key is even used as <kbd>Launcher</kbd> when connection a Windows keyboard. Another reason is that the launcher-key acts as a modifier key, so I needed a modifier as a substitution. I am hopeful that this even works during practice, at least with combinations that are not intercepted by Chrome OS. Would be great if you could report back on that. Thanks!

I am h

**Comment by Prometheus720** [comment]
I agree with the decision for meta.

I tried practicing these shortcuts on my Windows PC and there were a few that escaped the browser and did things, but not terribly.

However, I'm really having trouble on my real Chromebook. Most of the commands are escaping the browser. If helpful, I can give you a full list. For now it seems that anything using more/other modifiers than CTRL are getting intercepted. Some examples of what works:

CTRL + Number for tab navigation
CTRL + O for opening files
CTRL + R for refreshing

Also, there is a typo on "Sign out of google accont." Should say Google account.

And one final issue: CTRL + PLUS is failing on zoom in. But Chromebooks also accept CTRL + = and that actually does not get intercepted. So that is a quick fix.

**Comment by tkainrad** [comment]
Thanks a lot for reporting back! 

I fixed the typo and added <kbd>Ctrl</kbd>+<kbd>=</kbd> as an alternative for Zoom in.

I was afraid that practicing on a Chromebook would be problematic. Do you think it could help install the KeyCombiner Desktop app? It should be possible to install the Linux app on Chromebooks, right? Would also be very interesting for me if the instant lookup of the desktop app works then. 

Otherwise, I am not sure what could be done. Maybe there is a way to temporarily disable all the OS shortcuts in the system settings while practicing?
