### ISSUE TITLE
Cannot connect Google account to existing user

### ISSUE THREAD

**Issue by brimwats** [tkainrad/keycombiner#74]
**Describe the bug**
I was annoyed with how often keycombiner logged me out, so I decided to try logging into my google account to see if that made a difference. I used the oauth login, but...Signing in with Google Account Deletes account and all Data

**To Reproduce**
1. Make account with a gmail
2.  add collections, spend hours curating them, practice for weeks
3. sign in with a gmail and notice your collections are gone
~~4. try to login the normal way but find that that password is now incorrect.~~
^ this one resolved itself, but I'm worried one account will erase other—there are now two accounts with the same email

sorry for coming off as a bit salty but I am sad :(

**Comment by brimwats** [comment]
It looks like my account data is still okay on the website, but I can't export the keycombos and I'm worried desktop will soon erase the web version.

**Comment by brimwats** [comment]
Ah! I can login on desktop again and have things saved! but now I don't know which account will take priority with the same email

**Comment by tkainrad** [comment]
Hi! 
I will reply in more detail later. Just to put you at ease a bit: All your data is save! Please don't delete any of the accounts until I come back to you with a proper solution 😅

**Comment by tkainrad** [comment]
Currently, when you try to sign in with Google using the same mail address that is already set for an account that was signed up with mail+password, KeyCombiner will tell you that this is not possible and you should continue logging in via password.

However, in your case, KeyCombiner didn't recognize that the mail already exists because you previously signed up without dots in the first part of your mail address. While Gmail ignores these dots, KeyCombiner does not and thinks that there are two different accounts. 

The good news: Your existing account is fully functional. You can keep using it the way you are used to by using the email address (without dots) and password you signed up with.

If you want, you can also delete the new Google-connected account. It is entirely unrelated to your old account. 

---

> I was annoyed with how often keycombiner logged me out

KeyCombiner should only log you out after 30 days, never on the Desktop app. Did you experience different behaviour?

---

There is currently no way to switch to logging in via Google after signing up manually with mail+password. I will change that and make it easy to connect a Google account to an existing KeyCombiner account. Once that feature is live, you can connect your Google account to your old user account and log in via Google like you wanted.

**Comment by brimwats** [comment]
thanks for all this!! 

> KeyCombiner should only log you out after 30 days, never on the Desktop app. Did you experience different behaviour?

I definitely am being logged out more often than that, I try to use KC 2-3x a week and I usually have to log in about weekly. I can try to see if I can get an exact number of days!

**Comment by tkainrad** [comment]
> I will change that and make it easy to connect a Google account to an existing KeyCombiner account. 

**Happy to announce that this is now live!** 

There is a new settings item **Google SSO Settings** that lets you connect a Google account to your existing KeyCombiner account in order to use it for signing in. You can even add multiple accounts and subsequently use either to sign in. 

I recommend you delete your Google-connected account and then use this new feature to add the account to your old one.

---

> I definitely am being logged out more often than that, I try to use KC 2-3x a week and I usually have to log in about weekly. I can try to see if I can get an exact number of days!

Hmm, that's strange. Could it have to do with your browser settings? Does it happen with KeyCombiner Desktop also?

**Comment by brimwats** [comment]
thanks!!
