### ISSUE TITLE
longer collection names

### ISSUE THREAD

**Issue by yangkennyk** [tkainrad/keycombiner#8]
**Is your feature request related to a problem? Please describe.**
not critical but I noticed there was a character limit for my collection names. 

I'm sure the majority of the time I won't need a long collection name but I was trying to use

"Karabiner Vi Mode (rev 5) - [S as Trigger Key]" for adding https://ke-complex-modifications.pqrs.org/#vi_mode

**Describe the solution you'd like**
allow longer collection name

**Comment by tkainrad** [comment]
The character limit is basically for displaying purposes. If KeyCombiner has to shorten the collection name at a lot of places due to limited space, an increased limit will probably not help much.

However, KeyCombiner's interface has changed quite a bit since we decided on the exact limit. We will re-evaluate.

**Comment by tkainrad** [comment]
This has now been implemented:

![image](https://user-images.githubusercontent.com/7394822/112868370-4755f880-90bc-11eb-94cb-1f237d00149b.png)

The new collection name limit is 48.
If you need more than that, please try to use abbreviations instead. Similar to e.g. GitHub repos, collection names should ideally be short.
