### ISSUE TITLE
Karabiner modifiers and problems with uppercase keys after CSV import

### ISSUE THREAD

**Issue by yangkennyk** [tkainrad/keycombiner#9]
**Is your feature request related to a problem? Please describe.**
likely another edge case for me but I'm mapping the shorts cuts for https://ke-complex-modifications.pqrs.org/#vi_mode and I think the usage of character keys as a modifier isn't allowed so it shows it as an invalid key combination.

**Describe the solution you'd like**
would be nice to allow it although I'm not sure how complex that would be

**Describe alternatives you've considered**
I'm just adding them anyway and won't use the practice feature

**Additional context**
![image](https://user-images.githubusercontent.com/6680040/111915792-687c7080-8a4e-11eb-8b77-91ed2db6e829.png)

**Comment by tkainrad** [comment]
Hi, thanks for reporting this issue!

I see a few problems with these imported combinations:

1. KeyCombiner does not recognize slashes for setting alternatives. Please use the _or_ keyword and give full combinations on either side of the _or_. For example, `v h/j/k/l` should be `v h or v j or v k or v l`.
2. Key combinations should be specified all lowercase
3. Please note that space between keys means that they should be pressed as a sequence (one after the other). KeyCombiner will render this space as `>`. A plus means that the keys should be pressed at the same time. So, I think you don't want to have `v  0`, but rather `v+0`, according to your linked resource.

I believe these issues are the reason for why KeyCombiner deems these combinations invalid. Two non-modifier keys required to be pressed at the same time (e.g. `d+f`) would also be problematic during practice. However, at the moment KeyCombiner does not recognize such a combination as invalid. 

**Small Proposed Fix:**
KeyCombiner will soon convert everything to lowercase automatically. Thanks for highlighting this problem.
The other fixes, you will have to do yourself, if you want the warning icons to go away and use these combinations in practice:
1. use the _or_ keyword instead of slashes
2. use `+` when keys should be pressed at the same time, and ` ` when they should be pressed as a sequence

**Comment by tkainrad** [comment]
Automatic conversion to lowercase when importing keyboard shortcuts via CSV files is now live. If you delete and import again, some of these combinations will now be valid. For most, you would have to fix the slashes though.

**Comment by yangkennyk** [comment]
> Automatic conversion to lowercase when importing keyboard shortcuts via CSV files is now live. If you delete and import again, some of these combinations will now be valid. For most, you would have to fix the slashes though.

yeah initially I was using "or" so I would end up with

d+f h or d+f j or d+f k or d+f l

which was tedious ( I also realized I was spending too much time doing it) and just hard to grasp what was going on by looking at it in edit mode so I just copy and pasted from the docs.

a nice touch would be to trim space characters or simply allow them in the context of `d + f ` because I ended up needing to find and replace the spaces because it's invalid otherwise.

**Comment by tkainrad** [comment]
That's a great idea! Created a new issue (#11) for trimming whitespace around `+` and `or` operators. 

Allowing to use a slash for denoting alternatives for the non-modifier part of a shortcut is an interesting idea, too. However, it would make parsing during validation and for preparing as training input quite a bit more complex. I will keep the idea in mind though!
