### ISSUE TITLE
New Pricing option request

### ISSUE THREAD

**Issue by playmobilmeister** [tkainrad/keycombiner#96]
Hello Thomas,

I use KeyCombiner often and love it. I would love some of the Pro features but I am afraid I can not afford it. I was thinking: maybe you can create a middle option without all of the features, that is just
-Create unlimited collections
-Combined collection table

Pricing model- one time payment, need to pay for a new license every x years to receive updates.

**Comment by tkainrad** [comment]
Hi! 

I am glad you enjoy KeyCombiner! Unfortunately, doing one-time payments with a limited update period is not possible with KeyCombiner's technical architecture, where changes are shipped immediately and to everyone.

KeyCombiner's pricing is already very low and didn't increase since KeyCombiner launched. Furthermore, you won't lose access to any of your collections if you downgrade.

Still, I am happy to accommodate different situations. Especially for loyal users like yourself who have given valuable feedback many times. I will close this issue but contact you directly with an offer that might suit your needs.
